package infra.output;

import domain.output.SqlFileNamePolicy;

import java.io.IOException;

import java.nio.charset.StandardCharsets;

import java.nio.file.Files;

import java.nio.file.Path;

/**
 * Low-level SQL file writer.
 *
 * <p>Filename policy:
 * <pre>
 *   <mapper>.<queryId>.sql
 * </pre>
 */
public final class AliasSqlFileWriter {

    public Path write(Path outDir, String serviceClass, String namespace, String sqlId, String sqlText) {
        if (outDir == null) throw new IllegalArgumentException("outDir is null");

        try {
            Files.createDirectories(outDir);

            String fileName = SqlFileNamePolicy.build(namespace, sqlId);
            Path outFile = outDir.resolve(fileName);

            StringBuilder sb = new StringBuilder((sqlText == null ? 0 : sqlText.length()) + 64);
            sb.append("-- generated by sql-transformer\n");
            sb.append("-- serviceClass: ").append(nullToEmpty(serviceClass)).append("\n");
            sb.append("-- namespace   : ").append(nullToEmpty(namespace)).append("\n");
            sb.append("-- sqlId       : ").append(nullToEmpty(sqlId)).append("\n\n");

            if (sqlText != null) sb.append(sqlText);

            Files.writeString(outFile, sb.toString(), StandardCharsets.UTF_8);
            return outFile;
        } catch (IOException e) {
            throw new IllegalStateException("Failed to write SQL. outDir=" + outDir + ", namespace=" + namespace + ", sqlId=" + sqlId, e);
        }
    }

    private static String nullToEmpty(String s) {
        return s == null ? "" : s;
    }
}
